platform :ios, '10.0'
use_frameworks!

source 'git@github.com:applicaster/CocoaPods.git'
source 'https://cdn.cocoapods.org/'

pre_install do |installer|
    # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end

def shared_pods
 	pod 'ZappPlugins'
    pod 'MyAdvertisementPlugin', :path => 'MyAdvertisementPlugin.podspec'
end

target 'ZappAdvertisementPluginExample-iOS' do
    shared_pods
end