platform :ios, '10.0'
use_frameworks!

source 'git@github.com:applicaster/CocoaPods.git'

target 'PurchaseScreenPlugin' do
  pod 'ZappPlugins'
  pod 'ApplicasterIAP', :source => 'https://github.com/applicaster/applicaster-iap-framework'
end
