# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'git@github.com:applicaster/CocoaPods.git'

target 'PurchaseScreenPlugin' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PurchaseScreenPlugin

  pod 'ZappPlugins'
  pod 'ApplicasterIAP', :source => 'https://github.com/applicaster/applicaster-iap-framework'

end
